/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(correlate_access_code_bb_ts_fl.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c2abf3f758bedb508d5207437f574b4d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <reveng/correlate_access_code_bb_ts_fl.h>
// pydoc.h is automatically generated in the build directory
#include <correlate_access_code_bb_ts_fl_pydoc.h>

void bind_correlate_access_code_bb_ts_fl(py::module& m)
{

    using correlate_access_code_bb_ts_fl    = ::gr::reveng::correlate_access_code_bb_ts_fl;


    py::class_<correlate_access_code_bb_ts_fl, gr::block, gr::basic_block,
        std::shared_ptr<correlate_access_code_bb_ts_fl>>(m, "correlate_access_code_bb_ts_fl", D(correlate_access_code_bb_ts_fl))

        .def(py::init(&correlate_access_code_bb_ts_fl::make),
           py::arg("access_code"),
           py::arg("threshold"),
           py::arg("tag_name"),
           py::arg("len"),
           D(correlate_access_code_bb_ts_fl,make)
        )
        




        
        .def("set_access_code",&correlate_access_code_bb_ts_fl::set_access_code,       
            py::arg("access_code"),
            D(correlate_access_code_bb_ts_fl,set_access_code)
        )


        
        .def("access_code",&correlate_access_code_bb_ts_fl::access_code,       
            D(correlate_access_code_bb_ts_fl,access_code)
        )

        ;




}








